<a href="https://colab.research.google.com/github/abduvokhid25/numpy/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
mydataset = {
    'cars': ["Mers", "Bmw", "Ford", "Audi", "Lexus", "Toyota"],
    'counts': [3, 4, 6, 4, 5, 6]
}

df = pd.DataFrame(mydataset)
print(df)

     cars  counts
0    Mers       3
1     Bmw       4
2    Ford       6
3    Audi       4
4   Lexus       5
5  Toyota       6

In [ ]:

df.head() #default 5 raws

    cars  counts
0   Mers       3
1    Bmw       4
2   Ford       6
3   Audi       4
4  Lexus       5

In [ ]:
df.tail() # oxiridan 5 ta qator

     cars  counts
1     Bmw       4
2    Ford       6
3    Audi       4
4   Lexus       5
5  Toyota       6

In [ ]:
df.shape # tuzilishini olib beradi

(6, 2)

In [ ]:
df.columns # typeni korsatadi

Index(['cars', 'counts'], dtype='object')

In [ ]:
df.types

In [ ]:
df.describe(include = "all") # numerical column only

        cars    counts
count      6  6.000000
unique     6       NaN
top     Mers       NaN
freq       1       NaN
mean     NaN  4.666667
std      NaN  1.211060
min      NaN  3.000000
25%      NaN  4.000000
50%      NaN  4.500000
75%      NaN  5.750000
max      NaN  6.000000

In [ ]:
df.iloc[-1]

cars      Toyota
counts         6
Name: 5, dtype: object

In [ ]:
df[df["counts"] > 3]

     cars  counts
1     Bmw       4
2    Ford       6
3    Audi       4
4   Lexus       5
5  Toyota       6

In [ ]:
#df.mean(numeric_only=True)
df["counts"].mean()

np.float64(4.666666666666667)

In [ ]:
df.sum()

cars      MersBmwFordAudiLexusToyota
counts                            28
dtype: object

In [ ]:
df.min()

cars      Audi
counts       3
dtype: object

In [ ]:
df.max()

cars      Toyota
counts         6
dtype: object

In [ ]:
df.median(numeric_only=True)

counts    4.5
dtype: float64

In [ ]:
df.count()

cars      6
counts    6
dtype: int64

In [ ]:
import pandas as pd

mydataset = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
    'counts': [3, 7, 2, None, 1, 9, None]
}

df_missing = pd.DataFrame(mydataset)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     Ford     2.0
3    Tesla     NaN
4  Ferrari     1.0
5     Ford     9.0
6      BMW     NaN

In [ ]:
df_missing.isnull().sum()

NameError: name 'df_missing' is not defined

In [ ]:
df_missing.dropna(how="all")

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     Ford     2.0
3    Tesla     NaN
4  Ferrari     1.0
5     Ford     9.0
6      BMW     NaN

In [ ]:
df_missing.dropna(axis=1)

      cars
0      BMW
1    Volvo
2     Ford
3    Tesla
4  Ferrari
5     Ford
6      BMW

In [ ]:
df_missing.dropna(subset=['cars'])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     Ford     2.0
3    Tesla     NaN
4  Ferrari     1.0
5     Ford     9.0
6      BMW     NaN

In [ ]:
df_missing.fillna("unknown")

      cars   counts
0      BMW      3.0
1    Volvo      7.0
2     Ford      2.0
3    Tesla  unknown
4  Ferrari      1.0
5     Ford      9.0
6      BMW  unknown

In [41]:
df = pd.read_csv("Titanic-Dataset.csv")
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [43]:
df.to_excel("output.xlsx")

In [44]:
cars = pd.Series(["mers", "bmw", "tesla"])
print(cars)

0     mers
1      bmw
2    tesla
dtype: object

In [46]:
cars_series =df_missing['cars']
print (cars_series)

0        BMW
1      Volvo
2       Ford
3      Tesla
4    Ferrari
5       Ford
6        BMW
Name: cars, dtype: object